// Daftar pekerjaan standar yang biasa dipakai di form kependudukan Indonesia
// (mengikuti kategori pekerjaan pada KTP-el/KK ala Dukcapil). Dipakai bersama
// oleh form Tambah Warga dan Edit Warga supaya isian "pekerjaan" konsisten
// (dropdown, bukan teks bebas) — konsisten juga dengan tabel rincian
// "Jumlah Penduduk Berdasarkan Pekerjaan" di beranda publik.
//
// Urutan sengaja mengikuti urutan umum daftar pekerjaan KTP (bukan alfabet),
// "Lainnya" selalu di posisi terakhir sebagai fallback.
export const PEKERJAAN_OPTIONS = [
  "Belum/Tidak Bekerja",
  "Mengurus Rumah Tangga",
  "Pelajar/Mahasiswa",
  "Pensiunan",
  "Pegawai Negeri Sipil (PNS)",
  "Tentara Nasional Indonesia (TNI)",
  "Kepolisian RI (POLRI)",
  "Perangkat Desa",
  "Kepala Desa",
  "Petani/Pekebun",
  "Buruh Tani/Perkebunan",
  "Peternak",
  "Buruh Peternakan",
  "Nelayan/Perikanan",
  "Buruh Nelayan/Perikanan",
  "Pedagang",
  "Perdagangan",
  "Wiraswasta",
  "Karyawan Swasta",
  "Karyawan BUMN",
  "Karyawan BUMD",
  "Karyawan Honorer",
  "Buruh Harian Lepas",
  "Industri",
  "Konstruksi",
  "Transportasi",
  "Sopir",
  "Pelaut",
  "Tukang Cukur",
  "Tukang Listrik",
  "Tukang Batu",
  "Tukang Kayu",
  "Tukang Las/Pandai Besi",
  "Tukang Jahit",
  "Tukang Sol Sepatu",
  "Tukang Gigi",
  "Penata Rias",
  "Penata Rambut",
  "Penata Busana",
  "Mekanik",
  "Pembantu Rumah Tangga",
  "Juru Masak",
  "Dokter",
  "Bidan",
  "Perawat",
  "Apoteker",
  "Psikiater/Psikolog",
  "Guru",
  "Dosen",
  "Pengacara",
  "Notaris",
  "Arsitek",
  "Akuntan",
  "Konsultan",
  "Peneliti",
  "Wartawan",
  "Penyiar Televisi",
  "Penyiar Radio",
  "Seniman",
  "Perancang Busana",
  "Penerjemah",
  "Pilot",
  "Imam Masjid",
  "Ustadz/Mubaligh",
  "Pendeta",
  "Pastor",
  "Biarawati",
  "Lainnya",
];
